export { Service } from './service'
export { FunctionalApi } from './functionalApi'
export { FunctionalService } from './functionalService'
export { DynamoDB } from './externals/dynamoDB'
export { SimpleNotificationService } from './externals/sns'
export { S3Storage } from './externals/s3Storage'
export { callExtension } from './core/classExtensions'