export { Resource } from './resource'
export { Api } from './api'
export { FunctionalApi } from './functionalApi'
export { FunctionalService } from './functionalService'
export { DynamoTable } from './externals/dynamoTable'
export { SimpleNotificationService } from './externals/sns'
export { S3Storage } from './externals/s3Storage'
export { ApiGateway } from './externals/apiGateway'
export { callExtension } from './core/classExtensions'
export { Service } from './service'

export { PreHook } from './middleware/preHook'
export { PostHook } from './middleware/postHook'