export { Resource } from './resource'
export { Api } from './api'
export { FunctionalService } from './functionalService'
export { DynamoTable, DocumentClientApi } from './api/aws/dynamoTable'
export { SimpleNotificationService, SNSApi } from './api/aws/sns'
export { S3Storage, S3Api } from './api/aws/s3Storage'
export { ApiGateway } from './api/aws/apiGateway'
export { callExtension } from './core/callExtension'
export { Service } from './service'

export { PreHook } from './middleware/preHook'
export { PostHook } from './middleware/postHook'