export const CLASS_KEY_PREFIX = 'functionly:class:'

export const PARAMETER_PARAMKEY = 'functionly:param:parameters'
export const CLASS_DESCRIPTIONKEY = 'functionly:class:description'
export const CLASS_ROLEKEY = 'functionly:class:role'
export const CLASS_GROUP = 'functionly:class:group'
export const CLASS_ENVIRONMENTKEY = 'functionly:class:environment'
export const CLASS_MIDDLEWAREKEY = 'functionly:class:middleware'
export const CLASS_APIGATEWAYKEY = 'functionly:class:apigateway'
export const CLASS_CLOUDWATCHEVENT = 'functionly:class:cloudwatchevent'
export const CLASS_TAGKEY = 'functionly:class:tag'
export const CLASS_LOGKEY = 'functionly:class:log'
export const CLASS_INJECTABLEKEY = 'functionly:class:injectable'
export const CLASS_NAMEKEY = 'functionly:class:name'
export const CLASS_DYNAMOTABLECONFIGURATIONKEY = 'functionly:class:dynamoTableConfiguration'
export const CLASS_SNSCONFIGURATIONKEY = 'functionly:class:snsConfiguration'
export const CLASS_S3CONFIGURATIONKEY = 'functionly:class:s3Configuration'
export const CLASS_CLASSCONFIGKEY = 'functionly:class:classConfig'

export const CLASS_HTTPTRIGGER = 'functionly:class:httpTrigger'

export const CLASS_AZURENODEKEY = 'functionly:class:azurenode'

export const CLASS_AWSRUNTIMEKEY = 'functionly:class:awsruntime'
export const CLASS_AWSMEMORYSIZEKEY = 'functionly:class:awsmemorysize'
export const CLASS_AWSTIMEOUTKEY = 'functionly:class:awstimeout'
